# **Assignment**

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive

## **#1**

**- use "Read_CSV" method to link with your python and the file (TopSellingAlbums.csv)in your google drive.**

In [3]:
import pandas as pd
data = pd.read_csv("/content/gdrive/My Drive/TopSellingAlbums.csv")
data

            Artist                            Album  ...  Soundtrack Rating
0  Michael Jackson                         Thriller  ...         NaN   10.0
1            AC/DC                    Back in Black  ...         NaN    9.5
2       Pink Floyd        The Dark Side of the Moon  ...         NaN    9.0
3  Whitney Houston                    The Bodyguard  ...           Y    8.5
4        Meat Loaf                  Bat Out of Hell  ...         NaN    8.0
5           Eagles  Their Greatest Hits (1971-1975)  ...         NaN    7.5
6         Bee Gees             Saturday Night Fever  ...           Y    7.0
7    Fleetwood Mac                          Rumours  ...         NaN    6.5

[8 rows x 10 columns]

## **#2**

**- practice how to use iloc and loc methods**

In [49]:
print(data.iloc[0,0])
print()
print(data.loc[7,'Length'])
print()
print(data.loc[0:5, 'Artist'])
print()
print(data.iloc[0:5, 0])
print()
print(data.loc[ : ,'Length':'Released.1'])
print()
print(data.loc[ : , : ])
print()
print(data.iloc[ : , : ])
print()
sub_data = data.iloc[ : , 0:3]
print(sub_data)
print()
print(sub_data.iloc[3:6, 2])

Michael Jackson

0:40:01

0    Michael Jackson
1              AC/DC
2         Pink Floyd
3    Whitney Houston
4          Meat Loaf
5             Eagles
Name: Artist, dtype: object

0    Michael Jackson
1              AC/DC
2         Pink Floyd
3    Whitney Houston
4          Meat Loaf
Name: Artist, dtype: object

    Length                        Genre  ...  Claimed Sales (millions)  Released.1
0  0:42:19               pop, rock, R&B  ...                        65   30-Nov-82
1  0:42:11                    hard rock  ...                        50   25-Jul-80
2  0:42:49             progressive rock  ...                        45   01-Mar-73
3  0:57:44               R&B, soul, pop  ...                        44   17-Nov-92
4  0:46:33  hard rock, progressive rock  ...                        43   21-Oct-77
5  0:43:08   rock, soft rock, folk rock  ...                        42   17-Feb-76
6  1:15:54                        disco  ...                        40   15-Nov-77
7  0:40:01                    soft rock  ...                        40   04-Feb-77

[8 rows x 5 columns]

            Artist                            Album  ...  Soundtrack Rating
0  Michael Jackson                         Thriller  ...         NaN   10.0
1            AC/DC                    Back in Black  ...         NaN    9.5
2       Pink Floyd        The Dark Side of the Moon  ...         NaN    9.0
3  Whitney Houston                    The Bodyguard  ...           Y    8.5
4        Meat Loaf                  Bat Out of Hell  ...         NaN    8.0
5           Eagles  Their Greatest Hits (1971-1975)  ...         NaN    7.5
6         Bee Gees             Saturday Night Fever  ...           Y    7.0
7    Fleetwood Mac                          Rumours  ...         NaN    6.5

[8 rows x 10 columns]

            Artist                            Album  ...  Soundtrack Rating
0  Michael Jackson                         Thriller  ...         NaN   10.0
1            AC/DC                    Back in Black  ...         NaN    9.5
2       Pink Floyd        The Dark Side of the Moon  ...         NaN    9.0
3  Whitney Houston                    The Bodyguard  ...           Y    8.5
4        Meat Loaf                  Bat Out of Hell  ...         NaN    8.0
5           Eagles  Their Greatest Hits (1971-1975)  ...         NaN    7.5
6         Bee Gees             Saturday Night Fever  ...           Y    7.0
7    Fleetwood Mac                          Rumours  ...         NaN    6.5

[8 rows x 10 columns]

            Artist                            Album  Released
0  Michael Jackson                         Thriller      1982
1            AC/DC                    Back in Black      1980
2       Pink Floyd        The Dark Side of the Moon      1973
3  Whitney Houston                    The Bodyguard      1992
4        Meat Loaf                  Bat Out of Hell      1977
5           Eagles  Their Greatest Hits (1971-1975)      1976
6         Bee Gees             Saturday Night Fever      1977
7    Fleetwood Mac                          Rumours      1977

3    1992
4    1977
5    1976
Name: Released, dtype: int64

## **#3**

**- make your small database that only includes the following information:**

**Where both the "released year" was later than 1979 and "Music Recording Sales" was larger than 24.**

In [87]:
filter1 = data["Released"] > 1979
filter2 = data["Music Recording Sales (millions)"]>24

DB = data.where(filter1 & filter2)
DB

            Artist          Album  Released  ... Released.1 Soundtrack  Rating
0  Michael Jackson       Thriller    1982.0  ...  30-Nov-82        NaN    10.0
1            AC/DC  Back in Black    1980.0  ...  25-Jul-80        NaN     9.5
2              NaN            NaN       NaN  ...        NaN        NaN     NaN
3  Whitney Houston  The Bodyguard    1992.0  ...  17-Nov-92          Y     8.5
4              NaN            NaN       NaN  ...        NaN        NaN     NaN
5              NaN            NaN       NaN  ...        NaN        NaN     NaN
6              NaN            NaN       NaN  ...        NaN        NaN     NaN
7              NaN            NaN       NaN  ...        NaN        NaN     NaN

[8 rows x 10 columns]

## **#4**

**- from your own small database, find if their "Genre" includes "Rock"?**

In [167]:
# sol1) 

Genre = list(DB["Genre"])

Genre_later = []

for i in Genre:
  if (type(i)==str):
    Genre_later.append(i.split(', '))

for i in Genre_later:
  if 'rock' in i:
    print("Genre column in DB includes 'rock'")
    break

# sol2)

for i in range(len(DB['Genre'])):
  if(type(DB['Genre'][i])==str):
    if DB['Genre'][i].find('rock') != -1:
      print("Genre column in DB includes 'rock'")
      break

Genre column in DB includes 'rock'
Genre column in DB includes 'rock'